networks:
  ran-product-network:
services:
  # products:
  #   container_name: ran-product-management-net-app
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   networks:
  #     - ran-product-network
  #   ports:
  #     - "8090:8080"
  #   environment:
  #     - SERVER_PORT=:8090
  #     - DB_USERNAME=product
  #     - DB_PASSWORD=product
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_NAME=product
  #   depends_on:
  #     postgres:
  #       condition: service_started
  
  postgres:
    container_name: ran-product-management-pg
    image: postgres:17.2
    networks:
      - ran-product-network
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=product123
      - POSTGRES_DB=products
    restart: no
  
  mongodb:
    container_name: ran-product-management-mongodb
    image: mongodb/mongodb-community-server:8.0.0-ubuntu2204
    networks:
      - ran-product-network
    restart: no
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=product123
