networks:
  ran-product-net-network:
services:
  # products:
  #   container_name: ran-products-management-net-app
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   networks:
  #     - ran-product-net-network
  #   ports:
  #     - "8090:8080"
  #   environment:
  #     - SERVER_PORT=:8090
  #     - DB_USERNAME=product
  #     - DB_PASSWORD=product
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_NAME=product
  #   depends_on:
  #     postgres:
  #       condition: service_started
  
  postgres:
    container_name: ran-products-management-net-pg
    image: postgres:17.2
    networks:
      - ran-product-net-network
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=products
      - POSTGRES_PASSWORD=products
      - POSTGRES_DB=products
    restart: no

